# Generated by Django 5.0.6 on 2024-07-10 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("userApp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interest",
            name="message",
        ),
    ]
